Display the weighted result in the public part of the questions
coopdevs/decidim-module-action_delegator pull request #171
Opened 2024-03-06 08:24 UTC by antopalidi

fixes #170

2024-03-07 11:40 UTC, antopalidi commented
@microstudi Ivan, this pr is ready to review

2024-03-08 10:45 UTC, microstudi requested changes
looks very nice,
just a think, can we add the added files to the the lib/overrides_spec.rb to keep track of them?

2024-03-08 10:57 UTC, antopalidi commented
> looks very nice, just a think, can we add the added files to the the lib/overrides_spec.rb to keep track of them?

One of them had already been added, I added the second one

2024-03-11 10:12 UTC, microstudi approved these changes
nice job!

2024-03-11 10:12 UTC, merged