Add voting status for participants"
coopdevs/decidim-module-action_delegator pull request #176
Opened 2024-03-26 12:55 UTC by ElviaBth

2024-04-03 09:03 UTC, microstudi requested changes
Nice job Elvia,
we need to check for the multioption responses as well.
Left you a couple of comments

2024-04-03 09:03 UTC, microstudi commented on app/views/decidim/consultations/question_votes/_callout.html.erb
> +                        <p><%= translated_attribute(user_response.title) %></p>
```suggestion
                        <p title="<%= translated_attribute(user_response.title) %>"><%= t("booleans.true")%></p>
```

2024-04-03 09:12 UTC, ElviaBth commented on app/views/decidim/action_delegator/consultations/questions/_link_to_delegations.html.erb
> +        👉
Done

2024-04-03 09:20 UTC, ElviaBth commented on app/views/decidim/consultations/question_votes/_callout.html.erb
> +                        <p><%= translated_attribute(user_response.title) %></p>
Thanks, done.

2024-04-29 15:52 UTC, microstudi commented on app/views/decidim/consultations/question_votes/_callout.html.erb
> +<% alert_class = total_published_questions != voted_questions ? "alert" : "success" %>
```suggestion
<% alert_class = total_published_questions != voted_questions ? "warning" : "success" %>
```

2024-04-29 15:53 UTC, merged