Add max grants check in CreateDelegation
coopdevs/decidim-module-action_delegator pull request #27
Opened 2020-09-23 20:42 UTC by mllocs

2020-09-24 07:14 UTC, sauloperez commented on app/commands/decidim/action_delegator/admin/create_delegation.rb
> +          return broadcast(:max_grants) if max_grants?
Something like `above_max_grants` would be more explicit IMO, but it's not really a big deal. Just suggesting.

2020-09-25 14:40 UTC, microstudi requested changes
I'd just simply a method.

2020-09-25 14:40 UTC, microstudi commented on app/commands/decidim/action_delegator/admin/create_delegation.rb
> +        end
```suggestion
        def above_max_grants?
          grants_count >= form.setting.max_grants
        end
```
I think this can be simplified!

2020-09-28 14:56 UTC, sauloperez approved these changes

2020-09-29 06:50 UTC, sauloperez commented
I'm taking this as approved since your comment was addressed @microstudi

2020-09-29 07:50 UTC, merged